// src/demo.tsx
import { batch, createComputed, createMemo } from 'solid-js'
import { render } from 'solid-js/web'
import { createMutable, createStore, produce, reconcile } from 'solid-js/store'
import { range } from 'es-toolkit'

// import Intable from 'intable'
// import { log } from 'intable/utils'
// import { VirtualScrollPlugin } from 'intable/plugins/VirtualScrollPlugin'

import { Intable } from '../packages/intable/src'
// import '../packages/intable/src/theme/element-plus.scss'
import { log } from '../packages/intable/src/utils'
import { VirtualScrollPlugin } from '../packages/intable/src/plugins/VirtualScrollPlugin'
import { useSelector } from '../packages/intable/src/hooks/useSelector'
// import 'intable/theme/element-plus.scss'
// import 'intable/dist/theme/element-plus.scss'

const root = document.body.appendChild(document.createElement('div'))

const state = createMutable({ bool: true })

const cols = createMutable(range(10).map(e => ({ name: 'col_' + e, id: 'col_' + e, width: 80 })))
let data = createMutable(range(1000).map((e, i) => Object.fromEntries(cols.map(e => [e.id, i + 1]))))

// render(() => <input type='checkbox' checked={state.bool} onChange={(e) => state.bool = e.currentTarget.checked} />, root)
// render(() => <button onClick={() => data[0].col_1 = 'xxx'}>xxx</button>, root)

// const cols = [{name:'asd'},{}]
// const data = [{},{},{}]
// const data = [{},{},{}]

// cols[2].fixed = 'left'
// cols[0].editable = true
// cols[0].editor = 'select'
// cols[0].enum = { 1: 1, 2: 2, 3: 3 }
// cols[0].render = 'file'
cols.forEach(e => (e.editable = true))

// cols.at(-3)!.width = undefined
// cols.at(-1)!.width = undefined

data.forEach(e => e.g = e.col_0 % 10)
data.forEach(e => e.n = e.col_0 % 3)

// render(() => (
//   <Menu items={[
//     { label: 'xx' }
//   ]} />
// ), root)

render(() => <Intable
  class='w-50vw! h-40vh m-10'
  // class='m-10'
  // style='width: 50vw; height: 40vh;'
  rowDrag
  colDrag
  size='small'
  index={state.bool}
  stickyHeader={state.bool}
  columns={cols}
  onColumnsChange={v => batch(() => (cols.length = 0, cols.push(...v)))}
  data={data}
  onDataChange={v => batch(() => (data.length = 0, data.push(...v)))}
  border
  resizable={{ row: { enable: true } }}
  plugins={[
    VirtualScrollPlugin,
    // HistoryPlugin,
    // DiffPlugin,
  ]}
  expand={{ enable: true, render: ({ data }) => <div class='p-2 c-red'>{JSON.stringify(data)}</div> }}
  // rowGroup={{ fields: ['g', 'n'] }}
  // rowGroup={{ fields: ['g'] }}
  diff={{
    onCommit: (...arg) => log(arg)
  }}
  virtual={{
    // x: { enable: false },
    // y: { enable: false },
  }}
  rowSelection={{
    // enable: true,
    // multiple: true,
    // onChange: (selected, unselected) => log(selected, unselected)
  }}
/>, root)

// src/demo-vue.tsx
// import './index.scss'
// import 'virtual:uno.css'

// import { createApp, h, ref, watchEffect } from 'vue'
// import VueTable from '../packages/vue'

// import './theme/element-plus.scss'
// import { log } from './utils'

// const container = document.createElement('div')
// document.body.append(container)

// const data = ref([{ 1: 'x1', id: 1, date: '2016-05-03' }])
// setTimeout(() => {
//   data.value = [{ id: 1, date: '2016-05-03', name: 'Tom', address: 'No. 189, Grove St, Los Angeles' }, {  }, {}]
//   // data.value.push({})
// }, 1000);

// const selected = ref([])
// watchEffect(() => {
//   console.log(selected.value)
// })

// createApp(() => [
//   h(VueTable, {
//     style: '',
//     class: 'w-100 m-4',
//     data: data.value,
//     'onUpdate:data': v => data.value = v,
//     border: true,
//     index: true,
//     // size: 'small',
//     columns: [
//       { name: 'Date', id: 'date', editable: true, editOnInput: true, enum: { a: 1 }, editor: 'date' },
//       { name: 'Name', id: 'name' },
//       { name: 'Address', id: 'address', width: 250 },
//       // todo re render
//       { name: '4', id: '4', render: o => h('div', { class: 'c-red' }, '111'), fixed: 'right' },
//     ],
//     selected: selected.value,
//     'onUpdate:selected': v => selected.value = v,
//     rowSelection: { enable: true }
//   }),
// ])
//   .mount(container)
